# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 445)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(9, 9, 721, 391))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.toolBox = QtWidgets.QToolBox(self.splitter)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 154, 309))
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.btnList_Ini = QtWidgets.QToolButton(self.page)
        self.btnList_Ini.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnList_Ini.setObjectName("btnList_Ini")
        self.gridLayout.addWidget(self.btnList_Ini, 0, 0, 1, 1)
        self.btnList_Clear = QtWidgets.QToolButton(self.page)
        self.btnList_Clear.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnList_Clear.setObjectName("btnList_Clear")
        self.gridLayout.addWidget(self.btnList_Clear, 1, 0, 1, 1)
        self.btnList_Insert = QtWidgets.QToolButton(self.page)
        self.btnList_Insert.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnList_Insert.setObjectName("btnList_Insert")
        self.gridLayout.addWidget(self.btnList_Insert, 2, 0, 1, 1)
        self.btnList_Append = QtWidgets.QToolButton(self.page)
        self.btnList_Append.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnList_Append.setObjectName("btnList_Append")
        self.gridLayout.addWidget(self.btnList_Append, 3, 0, 1, 1)
        self.btnList_Delete = QtWidgets.QToolButton(self.page)
        self.btnList_Delete.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnList_Delete.setObjectName("btnList_Delete")
        self.gridLayout.addWidget(self.btnList_Delete, 4, 0, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/check2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page, icon, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 154, 309))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 154, 309))
        self.page_3.setObjectName("page_3")
        self.toolBox.addItem(self.page_3, "")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.tab_1)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.editCurItemText = QtWidgets.QLineEdit(self.groupBox)
        self.editCurItemText.setObjectName("editCurItemText")
        self.horizontalLayout.addWidget(self.editCurItemText)
        self.chkBoxList_Editable = QtWidgets.QCheckBox(self.groupBox)
        self.chkBoxList_Editable.setChecked(True)
        self.chkBoxList_Editable.setObjectName("chkBoxList_Editable")
        self.horizontalLayout.addWidget(self.chkBoxList_Editable)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnSelectItem = QtWidgets.QToolButton(self.groupBox_2)
        self.btnSelectItem.setMouseTracking(False)
        self.btnSelectItem.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.btnSelectItem.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnSelectItem.setAutoRaise(False)
        self.btnSelectItem.setObjectName("btnSelectItem")
        self.horizontalLayout_2.addWidget(self.btnSelectItem)
        self.btnSel_ALL = QtWidgets.QToolButton(self.groupBox_2)
        self.btnSel_ALL.setObjectName("btnSel_ALL")
        self.horizontalLayout_2.addWidget(self.btnSel_ALL)
        self.btnSel_None = QtWidgets.QToolButton(self.groupBox_2)
        self.btnSel_None.setObjectName("btnSel_None")
        self.horizontalLayout_2.addWidget(self.btnSel_None)
        self.btnSel_Invs = QtWidgets.QToolButton(self.groupBox_2)
        self.btnSel_Invs.setObjectName("btnSel_Invs")
        self.horizontalLayout_2.addWidget(self.btnSel_Invs)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/724.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon1)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        self.verticalLayout.addWidget(self.listWidget)
        self.verticalLayout_2.addWidget(self.frame)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.act_InitializationList = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/128.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_InitializationList.setIcon(icon2)
        self.act_InitializationList.setObjectName("act_InitializationList")
        self.act_ClearList = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/delete1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_ClearList.setIcon(icon3)
        self.act_ClearList.setObjectName("act_ClearList")
        self.act_Insert = QtWidgets.QAction(MainWindow)
        self.act_Insert.setEnabled(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/424.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_Insert.setIcon(icon4)
        self.act_Insert.setObjectName("act_Insert")
        self.act_AddItem = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/316.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_AddItem.setIcon(icon5)
        self.act_AddItem.setObjectName("act_AddItem")
        self.act_DelCurrentItem = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/324.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_DelCurrentItem.setIcon(icon6)
        self.act_DelCurrentItem.setObjectName("act_DelCurrentItem")
        self.act_Itemselection = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/124.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_Itemselection.setIcon(icon7)
        self.act_Itemselection.setObjectName("act_Itemselection")
        self.act_Exit = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_Exit.setIcon(icon8)
        self.act_Exit.setObjectName("act_Exit")
        self.act_AllSelect = QtWidgets.QAction(MainWindow)
        self.act_AllSelect.setObjectName("act_AllSelect")
        self.act_AllUnselect = QtWidgets.QAction(MainWindow)
        self.act_AllUnselect.setObjectName("act_AllUnselect")
        self.act_ReverseElection = QtWidgets.QAction(MainWindow)
        self.act_ReverseElection.setObjectName("act_ReverseElection")
        self.mainToolBar.addAction(self.act_InitializationList)
        self.mainToolBar.addAction(self.act_ClearList)
        self.mainToolBar.addAction(self.act_Insert)
        self.mainToolBar.addAction(self.act_AddItem)
        self.mainToolBar.addAction(self.act_DelCurrentItem)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.act_Itemselection.triggered.connect(self.act_ReverseElection.trigger)
        self.act_Exit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnList_Ini.setText(_translate("MainWindow", "btnList_Ini"))
        self.btnList_Clear.setText(_translate("MainWindow", "btnList_Clear"))
        self.btnList_Insert.setText(_translate("MainWindow", "btnList_Insert"))
        self.btnList_Append.setText(_translate("MainWindow", "btnList_Append"))
        self.btnList_Delete.setText(_translate("MainWindow", "btnList_Delete"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "QListWidget操作"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "QTreeWidget[空]"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "QTableWidget[空]"))
        self.label.setText(_translate("MainWindow", "当前项变化"))
        self.chkBoxList_Editable.setText(_translate("MainWindow", "可编辑"))
        self.btnSelectItem.setText(_translate("MainWindow", "btnSelectItem"))
        self.btnSel_ALL.setText(_translate("MainWindow", "btnSel_All"))
        self.btnSel_None.setText(_translate("MainWindow", "btnSel_None"))
        self.btnSel_Invs.setText(_translate("MainWindow", "btnSel_Invs"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "New Item2"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "QListWidget"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "QTreeWidget[空]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "QTableWidget[空]"))
        self.mainToolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.act_InitializationList.setText(_translate("MainWindow", "初始化列表"))
        self.act_InitializationList.setToolTip(_translate("MainWindow", "初始化列表"))
        self.act_ClearList.setText(_translate("MainWindow", "清除列表"))
        self.act_ClearList.setToolTip(_translate("MainWindow", "清除列表"))
        self.act_Insert.setText(_translate("MainWindow", "插入项"))
        self.act_Insert.setToolTip(_translate("MainWindow", "插入项"))
        self.act_AddItem.setText(_translate("MainWindow", "添加项"))
        self.act_AddItem.setToolTip(_translate("MainWindow", "添加项"))
        self.act_DelCurrentItem.setText(_translate("MainWindow", "删除当前项"))
        self.act_DelCurrentItem.setToolTip(_translate("MainWindow", "删除当前项"))
        self.act_Itemselection.setText(_translate("MainWindow", "项选择"))
        self.act_Itemselection.setToolTip(_translate("MainWindow", "项选择"))
        self.act_Exit.setText(_translate("MainWindow", "退出"))
        self.act_Exit.setToolTip(_translate("MainWindow", "退出"))
        self.act_AllSelect.setText(_translate("MainWindow", "全选"))
        self.act_AllUnselect.setText(_translate("MainWindow", "全不选"))
        self.act_AllUnselect.setToolTip(_translate("MainWindow", "全不选"))
        self.act_ReverseElection.setText(_translate("MainWindow", "反选"))
        self.act_ReverseElection.setToolTip(_translate("MainWindow", "反选"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
