# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(339, 255)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        Widget.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAlign_Left = QtWidgets.QPushButton(Widget)
        self.btnAlign_Left.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/508.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlign_Left.setIcon(icon)
        self.btnAlign_Left.setCheckable(True)
        self.btnAlign_Left.setChecked(True)
        self.btnAlign_Left.setAutoExclusive(True)
        self.btnAlign_Left.setAutoDefault(False)
        self.btnAlign_Left.setDefault(False)
        self.btnAlign_Left.setFlat(True)
        self.btnAlign_Left.setObjectName("btnAlign_Left")
        self.horizontalLayout.addWidget(self.btnAlign_Left)
        self.btnAlign_Center = QtWidgets.QPushButton(Widget)
        self.btnAlign_Center.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/510.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlign_Center.setIcon(icon1)
        self.btnAlign_Center.setCheckable(True)
        self.btnAlign_Center.setAutoExclusive(True)
        self.btnAlign_Center.setAutoDefault(False)
        self.btnAlign_Center.setDefault(False)
        self.btnAlign_Center.setFlat(True)
        self.btnAlign_Center.setObjectName("btnAlign_Center")
        self.horizontalLayout.addWidget(self.btnAlign_Center)
        self.btnAlign_Right = QtWidgets.QPushButton(Widget)
        self.btnAlign_Right.setEnabled(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/512.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlign_Right.setIcon(icon2)
        self.btnAlign_Right.setCheckable(True)
        self.btnAlign_Right.setAutoExclusive(True)
        self.btnAlign_Right.setAutoDefault(False)
        self.btnAlign_Right.setDefault(False)
        self.btnAlign_Right.setFlat(True)
        self.btnAlign_Right.setObjectName("btnAlign_Right")
        self.horizontalLayout.addWidget(self.btnAlign_Right)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(Widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnFont_Bold = QtWidgets.QPushButton(Widget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/500.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFont_Bold.setIcon(icon3)
        self.btnFont_Bold.setCheckable(True)
        self.btnFont_Bold.setObjectName("btnFont_Bold")
        self.horizontalLayout_2.addWidget(self.btnFont_Bold)
        self.btnFont_Italic = QtWidgets.QPushButton(Widget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/502.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFont_Italic.setIcon(icon4)
        self.btnFont_Italic.setCheckable(True)
        self.btnFont_Italic.setObjectName("btnFont_Italic")
        self.horizontalLayout_2.addWidget(self.btnFont_Italic)
        self.btnFont_UnderLine = QtWidgets.QPushButton(Widget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/504.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFont_UnderLine.setIcon(icon5)
        self.btnFont_UnderLine.setCheckable(True)
        self.btnFont_UnderLine.setObjectName("btnFont_UnderLine")
        self.horizontalLayout_2.addWidget(self.btnFont_UnderLine)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(Widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chkBox_Readonly = QtWidgets.QCheckBox(Widget)
        self.chkBox_Readonly.setObjectName("chkBox_Readonly")
        self.horizontalLayout_3.addWidget(self.chkBox_Readonly)
        self.checkBox_Enabled = QtWidgets.QCheckBox(Widget)
        self.checkBox_Enabled.setChecked(True)
        self.checkBox_Enabled.setObjectName("checkBox_Enabled")
        self.horizontalLayout_3.addWidget(self.checkBox_Enabled)
        self.check_ClearButton = QtWidgets.QCheckBox(Widget)
        self.check_ClearButton.setObjectName("check_ClearButton")
        self.horizontalLayout_3.addWidget(self.check_ClearButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.editInput = QtWidgets.QLineEdit(Widget)
        self.editInput.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.editInput.setFont(font)
        self.editInput.setObjectName("editInput")
        self.verticalLayout.addWidget(self.editInput)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)
        Widget.setTabOrder(self.btnAlign_Left, self.btnAlign_Center)
        Widget.setTabOrder(self.btnAlign_Center, self.btnAlign_Right)
        Widget.setTabOrder(self.btnAlign_Right, self.btnFont_Bold)
        Widget.setTabOrder(self.btnFont_Bold, self.btnFont_Italic)
        Widget.setTabOrder(self.btnFont_Italic, self.btnFont_UnderLine)
        Widget.setTabOrder(self.btnFont_UnderLine, self.chkBox_Readonly)
        Widget.setTabOrder(self.chkBox_Readonly, self.checkBox_Enabled)
        Widget.setTabOrder(self.checkBox_Enabled, self.check_ClearButton)
        Widget.setTabOrder(self.check_ClearButton, self.editInput)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Demo3_2,按钮的使用"))
        self.btnAlign_Left.setText(_translate("Widget", "局左"))
        self.btnAlign_Center.setText(_translate("Widget", "居中"))
        self.btnAlign_Right.setText(_translate("Widget", "居右"))
        self.btnFont_Bold.setText(_translate("Widget", "粗体"))
        self.btnFont_Italic.setText(_translate("Widget", "斜体"))
        self.btnFont_UnderLine.setText(_translate("Widget", "下划线"))
        self.chkBox_Readonly.setText(_translate("Widget", "Readonly"))
        self.checkBox_Enabled.setText(_translate("Widget", "Enabled"))
        self.check_ClearButton.setText(_translate("Widget", "ClearButtonEnabled"))
        self.editInput.setText(_translate("Widget", "测试显示文本"))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())

