# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 399)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(20, 10, 431, 301))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 429, 299))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LabPicture = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.LabPicture.setAlignment(QtCore.Qt.AlignCenter)
        self.LabPicture.setObjectName("LabPicture")
        self.verticalLayout.addWidget(self.LabPicture)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeFiles = QtWidgets.QTreeWidget(self.dockWidgetContents)
        self.treeFiles.setObjectName("treeFiles")
        self.treeFiles.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeFiles)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/15.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/31.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_2.setIcon(0, icon1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setIcon(0, icon1)
        self.verticalLayout_2.addWidget(self.treeFiles)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.act_AddDirectory = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/open3.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_AddDirectory.setIcon(icon2)
        self.act_AddDirectory.setObjectName("act_AddDirectory")
        self.act_AddFiles = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/824.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_AddFiles.setIcon(icon3)
        self.act_AddFiles.setObjectName("act_AddFiles")
        self.act_DelNode = QtWidgets.QAction(MainWindow)
        self.act_DelNode.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/delete1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_DelNode.setIcon(icon4)
        self.act_DelNode.setObjectName("act_DelNode")
        self.act_IterationgNodes = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/fold.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_IterationgNodes.setIcon(icon5)
        self.act_IterationgNodes.setObjectName("act_IterationgNodes")
        self.act_Exit = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/exit.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_Exit.setIcon(icon6)
        self.act_Exit.setObjectName("act_Exit")
        self.act_Amplification = QtWidgets.QAction(MainWindow)
        self.act_Amplification.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/418.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_Amplification.setIcon(icon7)
        self.act_Amplification.setObjectName("act_Amplification")
        self.act_Zoomout = QtWidgets.QAction(MainWindow)
        self.act_Zoomout.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/416.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_Zoomout.setIcon(icon8)
        self.act_Zoomout.setObjectName("act_Zoomout")
        self.act_ActualSize = QtWidgets.QAction(MainWindow)
        self.act_ActualSize.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/414.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_ActualSize.setIcon(icon9)
        self.act_ActualSize.setObjectName("act_ActualSize")
        self.act_FitWidth = QtWidgets.QAction(MainWindow)
        self.act_FitWidth.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/424.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_FitWidth.setIcon(icon10)
        self.act_FitWidth.setObjectName("act_FitWidth")
        self.act_SuitableHeight = QtWidgets.QAction(MainWindow)
        self.act_SuitableHeight.setEnabled(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/426.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_SuitableHeight.setIcon(icon11)
        self.act_SuitableHeight.setObjectName("act_SuitableHeight")
        self.act_FormFloating = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/814.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_FormFloating.setIcon(icon12)
        self.act_FormFloating.setObjectName("act_FormFloating")
        self.act_FormVisible = QtWidgets.QAction(MainWindow)
        self.act_FormVisible.setIcon(icon9)
        self.act_FormVisible.setObjectName("act_FormVisible")
        self.menu.addAction(self.act_AddDirectory)
        self.menu.addAction(self.act_AddFiles)
        self.menu.addAction(self.act_DelNode)
        self.menu.addAction(self.act_IterationgNodes)
        self.menu.addSeparator()
        self.menu.addAction(self.act_Exit)
        self.menu_2.addAction(self.act_Amplification)
        self.menu_2.addAction(self.act_Zoomout)
        self.menu_2.addAction(self.act_ActualSize)
        self.menu_2.addAction(self.act_FitWidth)
        self.menu_2.addAction(self.act_SuitableHeight)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.mainToolBar.addAction(self.act_AddDirectory)
        self.mainToolBar.addAction(self.act_AddFiles)
        self.mainToolBar.addAction(self.act_DelNode)
        self.mainToolBar.addAction(self.act_IterationgNodes)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.act_Amplification)
        self.mainToolBar.addAction(self.act_Zoomout)
        self.mainToolBar.addAction(self.act_ActualSize)
        self.mainToolBar.addAction(self.act_FitWidth)
        self.mainToolBar.addAction(self.act_SuitableHeight)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.act_FormFloating)
        self.mainToolBar.addAction(self.act_FormVisible)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.act_Exit)

        self.retranslateUi(MainWindow)
        self.act_Exit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Demo3_9 QTreeWidget,QDockWidget"))
        self.LabPicture.setText(_translate("MainWindow", "待显示图片"))
        self.menu.setTitle(_translate("MainWindow", "目录树"))
        self.menu_2.setTitle(_translate("MainWindow", "视图"))
        self.mainToolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "图片目录树"))
        self.treeFiles.headerItem().setText(0, _translate("MainWindow", "节点"))
        self.treeFiles.headerItem().setText(1, _translate("MainWindow", "节点类型"))
        __sortingEnabled = self.treeFiles.isSortingEnabled()
        self.treeFiles.setSortingEnabled(False)
        self.treeFiles.topLevelItem(0).setText(0, _translate("MainWindow", "图片文件"))
        self.treeFiles.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "分组节点"))
        self.treeFiles.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "图片节点"))
        self.treeFiles.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "分组2"))
        self.treeFiles.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "图片2"))
        self.treeFiles.setSortingEnabled(__sortingEnabled)
        self.act_AddDirectory.setText(_translate("MainWindow", "添加目录"))
        self.act_AddDirectory.setToolTip(_translate("MainWindow", "添加目录"))
        self.act_AddFiles.setText(_translate("MainWindow", "添加文件"))
        self.act_AddFiles.setToolTip(_translate("MainWindow", "添加文件"))
        self.act_DelNode.setText(_translate("MainWindow", "删除节点"))
        self.act_DelNode.setToolTip(_translate("MainWindow", "删除节点"))
        self.act_IterationgNodes.setText(_translate("MainWindow", "遍历节点"))
        self.act_IterationgNodes.setToolTip(_translate("MainWindow", "遍历节点"))
        self.act_Exit.setText(_translate("MainWindow", "退出"))
        self.act_Exit.setToolTip(_translate("MainWindow", "退出"))
        self.act_Amplification.setText(_translate("MainWindow", "放大"))
        self.act_Amplification.setToolTip(_translate("MainWindow", "放大"))
        self.act_Zoomout.setText(_translate("MainWindow", "缩小"))
        self.act_Zoomout.setToolTip(_translate("MainWindow", "缩小"))
        self.act_ActualSize.setText(_translate("MainWindow", "实际大小"))
        self.act_FitWidth.setText(_translate("MainWindow", "适合宽度"))
        self.act_SuitableHeight.setText(_translate("MainWindow", "适合高度"))
        self.act_FormFloating.setText(_translate("MainWindow", "窗体浮动"))
        self.act_FormVisible.setText(_translate("MainWindow", "窗体可见"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
