# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(670, 416)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_Open = QtWidgets.QPushButton(self.groupBox)
        self.btn_Open.setObjectName("btn_Open")
        self.gridLayout_2.addWidget(self.btn_Open, 0, 0, 1, 1)
        self.btn_ProgressDialog = QtWidgets.QPushButton(self.groupBox)
        self.btn_ProgressDialog.setObjectName("btn_ProgressDialog")
        self.gridLayout_2.addWidget(self.btn_ProgressDialog, 3, 0, 1, 1)
        self.btn_ChooseColor = QtWidgets.QPushButton(self.groupBox)
        self.btn_ChooseColor.setObjectName("btn_ChooseColor")
        self.gridLayout_2.addWidget(self.btn_ChooseColor, 2, 0, 1, 1)
        self.btn_ChooseFont = QtWidgets.QPushButton(self.groupBox)
        self.btn_ChooseFont.setObjectName("btn_ChooseFont")
        self.gridLayout_2.addWidget(self.btn_ChooseFont, 2, 1, 1, 1)
        self.btn_Save = QtWidgets.QPushButton(self.groupBox)
        self.btn_Save.setObjectName("btn_Save")
        self.gridLayout_2.addWidget(self.btn_Save, 1, 1, 1, 1)
        self.btn_OpenMultipleFiles = QtWidgets.QPushButton(self.groupBox)
        self.btn_OpenMultipleFiles.setObjectName("btn_OpenMultipleFiles")
        self.gridLayout_2.addWidget(self.btn_OpenMultipleFiles, 0, 1, 1, 1)
        self.btn_ChooseExistiongDirectory = QtWidgets.QPushButton(self.groupBox)
        self.btn_ChooseExistiongDirectory.setObjectName("btn_ChooseExistiongDirectory")
        self.gridLayout_2.addWidget(self.btn_ChooseExistiongDirectory, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_MSGquestion = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_MSGquestion.setObjectName("btn_MSGquestion")
        self.gridLayout_3.addWidget(self.btn_MSGquestion, 0, 0, 1, 1)
        self.btn_MSGinformation = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_MSGinformation.setObjectName("btn_MSGinformation")
        self.gridLayout_3.addWidget(self.btn_MSGinformation, 0, 1, 1, 1)
        self.btn_MSGwarning = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_MSGwarning.setObjectName("btn_MSGwarning")
        self.gridLayout_3.addWidget(self.btn_MSGwarning, 1, 0, 1, 1)
        self.btn_MSGcritical = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_MSGcritical.setObjectName("btn_MSGcritical")
        self.gridLayout_3.addWidget(self.btn_MSGcritical, 1, 1, 1, 1)
        self.btn_MSGabout = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_MSGabout.setObjectName("btn_MSGabout")
        self.gridLayout_3.addWidget(self.btn_MSGabout, 2, 0, 1, 1)
        self.btn_MSGaboutQt = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_MSGaboutQt.setObjectName("btn_MSGaboutQt")
        self.gridLayout_3.addWidget(self.btn_MSGaboutQt, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_EnterInteger = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_EnterInteger.setObjectName("btn_EnterInteger")
        self.gridLayout_4.addWidget(self.btn_EnterInteger, 0, 1, 1, 1)
        self.btn_EnterFloat = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_EnterFloat.setObjectName("btn_EnterFloat")
        self.gridLayout_4.addWidget(self.btn_EnterFloat, 1, 0, 1, 1)
        self.btn_InputString = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_InputString.setObjectName("btn_InputString")
        self.gridLayout_4.addWidget(self.btn_InputString, 0, 0, 1, 1)
        self.btn_EntrySelectionInput = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_EntrySelectionInput.setObjectName("btn_EntrySelectionInput")
        self.gridLayout_4.addWidget(self.btn_EntrySelectionInput, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_4)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/212.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_20.setIcon(icon)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_4)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_21.setIcon(icon1)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout.addWidget(self.pushButton_21)
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)

        self.retranslateUi(Dialog)
        self.pushButton_20.clicked.connect(self.plainTextEdit.clear)
        self.pushButton_21.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Demo6_1,标准对话框的使用"))
        self.groupBox.setTitle(_translate("Dialog", "标准对话框"))
        self.btn_Open.setText(_translate("Dialog", "打开一个文件"))
        self.btn_ProgressDialog.setText(_translate("Dialog", "进度对话框"))
        self.btn_ChooseColor.setText(_translate("Dialog", "选择颜色"))
        self.btn_ChooseFont.setText(_translate("Dialog", "选择字体"))
        self.btn_Save.setText(_translate("Dialog", "保存文件"))
        self.btn_OpenMultipleFiles.setText(_translate("Dialog", "打开多个文件"))
        self.btn_ChooseExistiongDirectory.setText(_translate("Dialog", "选择已有目录"))
        self.groupBox_2.setTitle(_translate("Dialog", "标准消息框QMessageBox"))
        self.btn_MSGquestion.setText(_translate("Dialog", "question"))
        self.btn_MSGinformation.setText(_translate("Dialog", "information"))
        self.btn_MSGwarning.setText(_translate("Dialog", "warning"))
        self.btn_MSGcritical.setText(_translate("Dialog", "critical"))
        self.btn_MSGabout.setText(_translate("Dialog", "about"))
        self.btn_MSGaboutQt.setText(_translate("Dialog", "aboutQt"))
        self.groupBox_3.setTitle(_translate("Dialog", "标准输入对话框QInputDialog"))
        self.btn_EnterInteger.setText(_translate("Dialog", "输入整数"))
        self.btn_EnterFloat.setText(_translate("Dialog", "输入浮点数"))
        self.btn_InputString.setText(_translate("Dialog", "输入字符串"))
        self.btn_EntrySelectionInput.setText(_translate("Dialog", "条目选择输入"))
        self.pushButton_20.setText(_translate("Dialog", "清除文本框内容"))
        self.pushButton_21.setText(_translate("Dialog", "退出"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
